// This file is generated by icon spritesheet generator

export type IconName =
  | "Test"
  | "De"
  | "C"
  | "B"
  | "A"

export const iconNames = [
  "Test",
  "De",
  "C",
  "B",
  "A",
] as const
