// This file is generated by icon spritesheet generator

export const iconNames = [
  "Test",
  "De",
  "C",
  "BasicShapes",
  "B",
  "A",
] as const

export type IconName = typeof iconNames[number]
